timezone: America/Los_Angeles
encoding: UTF-8
lang: en-US
branch: gh-pages
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-github-metadata
  - jekyll-admin
permalink: "/:year/:month/:day/:title/"
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      comments: true
  - scope:
      path: ''
      type: pages
    values:
      layout: page
      comments: false

gist:
  noscript: false  

# Permalinks
future: true

# Setup
title: Jekyll Semantic
tagline: A GH Pages Concept Test
url: https://staginggrounds.github.io/jekyll-semantic
baseurl: '/'
#baseurl:          /
author:
 name: Ray Anthony
 url: https://twitter.com/dockrtc
 email: info@dockrtc.com
 twitter: https://twitter.com/rayanthonyrcc/
 twitter_username: rayanthonyrcc
 github_username: rayantony
 aboutme_username: https://about.me/rayanthony
 lastfm_username: deadflowers
 pandora_username: ray517
 codepen_username: rayrc
 jsfiddle_username: rayrc
# Custom vars
version: 1.0.0
github:
 repo: https://github.com/staginggrounds/jekyll-semantic
markdown: kramdown
highlighter: pygments
kramdown:
input: GFM
syntax_highlighter: rouge
version: 1.0.0

contact_links:
  - name: Twitter
    url: https://twitter.com/rayanthonyrcc
    icon: twitter
  - name: Google
#    url: https://plus.google.com/xxx?rel=author
    icon: google-plus
  - name: GitHub
    url: https://github.com/rayantony
    icon: github
  - name: Keybase
#    url: https://keybase.io/rayanthony
    icon: key

amazon:
#  affiliates_tag: 
