# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Jekyll Semantic
tagline:          A GH Pages Concept Test
url:              https://staginggrounds.github.io/jekyll-semantic
paginate:         1
baseurl:          /
author:
  name:           Ray Anthony
  url:            https://twitter.com/dockrtc
  email:          info@dockrtc.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/staginggrounds/jekyll-semantic
